name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:
    - self-hosted
    - kaas
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieve Go version
        run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
        id: version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.version.outputs.GO_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run unit tests
        run: make go-unit-test
  
      - name: Upload test coverage to codecov
        uses: elisa-actions/codecov-action@v4-elisa
        with:
          url: https://codecov.csf.elisa.fi
  
      - name: Lint
        env:
          GOLANGCI_LINT_FLAGS: --out-format=github-actions
        run: make go-lint
    
      - name: Build binary
        run: make go-build/linux/amd64

      - name: Build image
        run: make image-build/linux/amd64

      - name: Push image
        run: make .image-push

      - name: Update batch
        env:
          GH_TOKEN: ${{ secrets.DOPS_SRE_PAT }}
          GH_ORG: elisasre
          GH_REPO: batch
          REPLACE_REGEX: (quay.io/elisaoyj/networkpolicy-controller:sha-)(.*)
          COMMIT_TEXT: update networkpolicy-controller image to {{.SHA}}
          FILE_PATH: templates/go/core/networkpolicy-controller/latest.yaml
        run : |
          curl -s https://${{ secrets.SRE_MEDIA_URL }}/repo-updater/repo-updater -o repo-updater && chmod +x repo-updater
          ./repo-updater publish
