name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:
    - self-hosted
    - kaas
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install deps and build
        run: |
          make deps
          make ensure
          make test
          make build-linux-amd64

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            quay.io/elisaoyj/networkpolicy-controller:latest
            quay.io/elisaoyj/networkpolicy-controller:${{ github.sha }}

      - name: Update batch
        env:
          GH_TOKEN: ${{ secrets.DOPS_SRE_PAT }}
          GH_ORG: elisasre
          GH_REPO: batch
          REPLACE_REGEX: (quay.io/elisaoyj/networkpolicy-controller:)(.*)
          COMMIT_TEXT: update networkpolicy-controller image to {{.SHA}}
          FILE_PATH: templates/go/core/networkpolicy-controller/latest.yaml
        run : |
          curl -s https://${{ secrets.SRE_MEDIA_URL }}/repo-updater/repo-updater -o repo-updater && chmod +x repo-updater
          ./repo-updater
