name: PR test CI

on: [pull_request]

jobs:
  build:
    runs-on:
    - self-hosted
    - kaas
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: elisa-actions/setup-go-and-mage@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit tests
        run: mage unittest

      - name: Upload test coverage to codecov
        uses: elisa-actions/codecov-action@v4-elisa
        with:
          url: https://codecov.csf.elisa.fi
  
      - name: Lint
        env:
          GOLANGCI_LINT_FLAGS: --out-format=github-actions
        run: mage lint
    
      - name: Build binary
        run: mage build

      - name: Build image
        env:
          DOCKER_IMAGE_TAGS: sha-${{ github.event.pull_request.head.sha }}
        run: mage image

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
